/*
The Span API

API for device, collection, output and firmware management

API version: 4.6.0 truthful-holli
Contact: dev@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanapi

import (
	"encoding/json"
)

// checks if the DeviceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceStats{}

// DeviceStats This is the statistics for a single device
type DeviceStats struct {
	BytesUpstreamMb *float32 `json:"bytesUpstreamMb,omitempty"`
	BytesDownstreamMb *float32 `json:"bytesDownstreamMb,omitempty"`
	MessagesUpstream *int32 `json:"messagesUpstream,omitempty"`
	MessagesDownstream *int32 `json:"messagesDownstream,omitempty"`
	SessionCount *int32 `json:"sessionCount,omitempty"`
}

// NewDeviceStats instantiates a new DeviceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceStats() *DeviceStats {
	this := DeviceStats{}
	return &this
}

// NewDeviceStatsWithDefaults instantiates a new DeviceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceStatsWithDefaults() *DeviceStats {
	this := DeviceStats{}
	return &this
}

// GetBytesUpstreamMb returns the BytesUpstreamMb field value if set, zero value otherwise.
func (o *DeviceStats) GetBytesUpstreamMb() float32 {
	if o == nil || IsNil(o.BytesUpstreamMb) {
		var ret float32
		return ret
	}
	return *o.BytesUpstreamMb
}

// GetBytesUpstreamMbOk returns a tuple with the BytesUpstreamMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetBytesUpstreamMbOk() (*float32, bool) {
	if o == nil || IsNil(o.BytesUpstreamMb) {
		return nil, false
	}
	return o.BytesUpstreamMb, true
}

// HasBytesUpstreamMb returns a boolean if a field has been set.
func (o *DeviceStats) HasBytesUpstreamMb() bool {
	if o != nil && !IsNil(o.BytesUpstreamMb) {
		return true
	}

	return false
}

// SetBytesUpstreamMb gets a reference to the given float32 and assigns it to the BytesUpstreamMb field.
func (o *DeviceStats) SetBytesUpstreamMb(v float32) {
	o.BytesUpstreamMb = &v
}

// GetBytesDownstreamMb returns the BytesDownstreamMb field value if set, zero value otherwise.
func (o *DeviceStats) GetBytesDownstreamMb() float32 {
	if o == nil || IsNil(o.BytesDownstreamMb) {
		var ret float32
		return ret
	}
	return *o.BytesDownstreamMb
}

// GetBytesDownstreamMbOk returns a tuple with the BytesDownstreamMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetBytesDownstreamMbOk() (*float32, bool) {
	if o == nil || IsNil(o.BytesDownstreamMb) {
		return nil, false
	}
	return o.BytesDownstreamMb, true
}

// HasBytesDownstreamMb returns a boolean if a field has been set.
func (o *DeviceStats) HasBytesDownstreamMb() bool {
	if o != nil && !IsNil(o.BytesDownstreamMb) {
		return true
	}

	return false
}

// SetBytesDownstreamMb gets a reference to the given float32 and assigns it to the BytesDownstreamMb field.
func (o *DeviceStats) SetBytesDownstreamMb(v float32) {
	o.BytesDownstreamMb = &v
}

// GetMessagesUpstream returns the MessagesUpstream field value if set, zero value otherwise.
func (o *DeviceStats) GetMessagesUpstream() int32 {
	if o == nil || IsNil(o.MessagesUpstream) {
		var ret int32
		return ret
	}
	return *o.MessagesUpstream
}

// GetMessagesUpstreamOk returns a tuple with the MessagesUpstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetMessagesUpstreamOk() (*int32, bool) {
	if o == nil || IsNil(o.MessagesUpstream) {
		return nil, false
	}
	return o.MessagesUpstream, true
}

// HasMessagesUpstream returns a boolean if a field has been set.
func (o *DeviceStats) HasMessagesUpstream() bool {
	if o != nil && !IsNil(o.MessagesUpstream) {
		return true
	}

	return false
}

// SetMessagesUpstream gets a reference to the given int32 and assigns it to the MessagesUpstream field.
func (o *DeviceStats) SetMessagesUpstream(v int32) {
	o.MessagesUpstream = &v
}

// GetMessagesDownstream returns the MessagesDownstream field value if set, zero value otherwise.
func (o *DeviceStats) GetMessagesDownstream() int32 {
	if o == nil || IsNil(o.MessagesDownstream) {
		var ret int32
		return ret
	}
	return *o.MessagesDownstream
}

// GetMessagesDownstreamOk returns a tuple with the MessagesDownstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetMessagesDownstreamOk() (*int32, bool) {
	if o == nil || IsNil(o.MessagesDownstream) {
		return nil, false
	}
	return o.MessagesDownstream, true
}

// HasMessagesDownstream returns a boolean if a field has been set.
func (o *DeviceStats) HasMessagesDownstream() bool {
	if o != nil && !IsNil(o.MessagesDownstream) {
		return true
	}

	return false
}

// SetMessagesDownstream gets a reference to the given int32 and assigns it to the MessagesDownstream field.
func (o *DeviceStats) SetMessagesDownstream(v int32) {
	o.MessagesDownstream = &v
}

// GetSessionCount returns the SessionCount field value if set, zero value otherwise.
func (o *DeviceStats) GetSessionCount() int32 {
	if o == nil || IsNil(o.SessionCount) {
		var ret int32
		return ret
	}
	return *o.SessionCount
}

// GetSessionCountOk returns a tuple with the SessionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetSessionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SessionCount) {
		return nil, false
	}
	return o.SessionCount, true
}

// HasSessionCount returns a boolean if a field has been set.
func (o *DeviceStats) HasSessionCount() bool {
	if o != nil && !IsNil(o.SessionCount) {
		return true
	}

	return false
}

// SetSessionCount gets a reference to the given int32 and assigns it to the SessionCount field.
func (o *DeviceStats) SetSessionCount(v int32) {
	o.SessionCount = &v
}

func (o DeviceStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BytesUpstreamMb) {
		toSerialize["bytesUpstreamMb"] = o.BytesUpstreamMb
	}
	if !IsNil(o.BytesDownstreamMb) {
		toSerialize["bytesDownstreamMb"] = o.BytesDownstreamMb
	}
	if !IsNil(o.MessagesUpstream) {
		toSerialize["messagesUpstream"] = o.MessagesUpstream
	}
	if !IsNil(o.MessagesDownstream) {
		toSerialize["messagesDownstream"] = o.MessagesDownstream
	}
	if !IsNil(o.SessionCount) {
		toSerialize["sessionCount"] = o.SessionCount
	}
	return toSerialize, nil
}

type NullableDeviceStats struct {
	value *DeviceStats
	isSet bool
}

func (v NullableDeviceStats) Get() *DeviceStats {
	return v.value
}

func (v *NullableDeviceStats) Set(val *DeviceStats) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceStats) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceStats(val *DeviceStats) *NullableDeviceStats {
	return &NullableDeviceStats{value: val, isSet: true}
}

func (v NullableDeviceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


