/*
The Span API

API for device, collection, output and firmware management

API version: 5.0.2 subversive-jamila
Contact: dev@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanapi

import (
	"encoding/json"
)

// checks if the UpdateGatewayBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGatewayBody{}

// UpdateGatewayBody struct for UpdateGatewayBody
type UpdateGatewayBody struct {
	Name *string `json:"name,omitempty"`
	CollectionId *string `json:"collectionId,omitempty"`
	Type *GatewayType `json:"type,omitempty"`
	Config *GatewayConfig `json:"config,omitempty"`
	Tags *map[string]string `json:"tags,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
}

// NewUpdateGatewayBody instantiates a new UpdateGatewayBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGatewayBody() *UpdateGatewayBody {
	this := UpdateGatewayBody{}
	var type_ GatewayType = GATEWAYTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// NewUpdateGatewayBodyWithDefaults instantiates a new UpdateGatewayBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGatewayBodyWithDefaults() *UpdateGatewayBody {
	this := UpdateGatewayBody{}
	var type_ GatewayType = GATEWAYTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateGatewayBody) SetName(v string) {
	o.Name = &v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetCollectionId() string {
	if o == nil || IsNil(o.CollectionId) {
		var ret string
		return ret
	}
	return *o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionId) {
		return nil, false
	}
	return o.CollectionId, true
}

// HasCollectionId returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasCollectionId() bool {
	if o != nil && !IsNil(o.CollectionId) {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given string and assigns it to the CollectionId field.
func (o *UpdateGatewayBody) SetCollectionId(v string) {
	o.CollectionId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetType() GatewayType {
	if o == nil || IsNil(o.Type) {
		var ret GatewayType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetTypeOk() (*GatewayType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given GatewayType and assigns it to the Type field.
func (o *UpdateGatewayBody) SetType(v GatewayType) {
	o.Type = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetConfig() GatewayConfig {
	if o == nil || IsNil(o.Config) {
		var ret GatewayConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetConfigOk() (*GatewayConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given GatewayConfig and assigns it to the Config field.
func (o *UpdateGatewayBody) SetConfig(v GatewayConfig) {
	o.Config = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetTags() map[string]string {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetTagsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *UpdateGatewayBody) SetTags(v map[string]string) {
	o.Tags = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UpdateGatewayBody) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGatewayBody) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateGatewayBody) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UpdateGatewayBody) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o UpdateGatewayBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGatewayBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CollectionId) {
		toSerialize["collectionId"] = o.CollectionId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableUpdateGatewayBody struct {
	value *UpdateGatewayBody
	isSet bool
}

func (v NullableUpdateGatewayBody) Get() *UpdateGatewayBody {
	return v.value
}

func (v *NullableUpdateGatewayBody) Set(val *UpdateGatewayBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGatewayBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGatewayBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGatewayBody(val *UpdateGatewayBody) *NullableUpdateGatewayBody {
	return &NullableUpdateGatewayBody{value: val, isSet: true}
}

func (v NullableUpdateGatewayBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGatewayBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


