/*
The Span API

API for device, collection, output and firmware management

API version: 4.9.6 authoritarian-betty
Contact: dev@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanapi

import (
	"encoding/json"
)

// checks if the DeviceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceStats{}

// DeviceStats This is the statistics for a single device
type DeviceStats struct {
	BytesUpstream *string `json:"bytesUpstream,omitempty"`
	BytesDownstream *string `json:"bytesDownstream,omitempty"`
	MessagesUpstream *string `json:"messagesUpstream,omitempty"`
	MessagesDownstream *string `json:"messagesDownstream,omitempty"`
	SessionCount *int32 `json:"sessionCount,omitempty"`
}

// NewDeviceStats instantiates a new DeviceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceStats() *DeviceStats {
	this := DeviceStats{}
	return &this
}

// NewDeviceStatsWithDefaults instantiates a new DeviceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceStatsWithDefaults() *DeviceStats {
	this := DeviceStats{}
	return &this
}

// GetBytesUpstream returns the BytesUpstream field value if set, zero value otherwise.
func (o *DeviceStats) GetBytesUpstream() string {
	if o == nil || IsNil(o.BytesUpstream) {
		var ret string
		return ret
	}
	return *o.BytesUpstream
}

// GetBytesUpstreamOk returns a tuple with the BytesUpstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetBytesUpstreamOk() (*string, bool) {
	if o == nil || IsNil(o.BytesUpstream) {
		return nil, false
	}
	return o.BytesUpstream, true
}

// HasBytesUpstream returns a boolean if a field has been set.
func (o *DeviceStats) HasBytesUpstream() bool {
	if o != nil && !IsNil(o.BytesUpstream) {
		return true
	}

	return false
}

// SetBytesUpstream gets a reference to the given string and assigns it to the BytesUpstream field.
func (o *DeviceStats) SetBytesUpstream(v string) {
	o.BytesUpstream = &v
}

// GetBytesDownstream returns the BytesDownstream field value if set, zero value otherwise.
func (o *DeviceStats) GetBytesDownstream() string {
	if o == nil || IsNil(o.BytesDownstream) {
		var ret string
		return ret
	}
	return *o.BytesDownstream
}

// GetBytesDownstreamOk returns a tuple with the BytesDownstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetBytesDownstreamOk() (*string, bool) {
	if o == nil || IsNil(o.BytesDownstream) {
		return nil, false
	}
	return o.BytesDownstream, true
}

// HasBytesDownstream returns a boolean if a field has been set.
func (o *DeviceStats) HasBytesDownstream() bool {
	if o != nil && !IsNil(o.BytesDownstream) {
		return true
	}

	return false
}

// SetBytesDownstream gets a reference to the given string and assigns it to the BytesDownstream field.
func (o *DeviceStats) SetBytesDownstream(v string) {
	o.BytesDownstream = &v
}

// GetMessagesUpstream returns the MessagesUpstream field value if set, zero value otherwise.
func (o *DeviceStats) GetMessagesUpstream() string {
	if o == nil || IsNil(o.MessagesUpstream) {
		var ret string
		return ret
	}
	return *o.MessagesUpstream
}

// GetMessagesUpstreamOk returns a tuple with the MessagesUpstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetMessagesUpstreamOk() (*string, bool) {
	if o == nil || IsNil(o.MessagesUpstream) {
		return nil, false
	}
	return o.MessagesUpstream, true
}

// HasMessagesUpstream returns a boolean if a field has been set.
func (o *DeviceStats) HasMessagesUpstream() bool {
	if o != nil && !IsNil(o.MessagesUpstream) {
		return true
	}

	return false
}

// SetMessagesUpstream gets a reference to the given string and assigns it to the MessagesUpstream field.
func (o *DeviceStats) SetMessagesUpstream(v string) {
	o.MessagesUpstream = &v
}

// GetMessagesDownstream returns the MessagesDownstream field value if set, zero value otherwise.
func (o *DeviceStats) GetMessagesDownstream() string {
	if o == nil || IsNil(o.MessagesDownstream) {
		var ret string
		return ret
	}
	return *o.MessagesDownstream
}

// GetMessagesDownstreamOk returns a tuple with the MessagesDownstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetMessagesDownstreamOk() (*string, bool) {
	if o == nil || IsNil(o.MessagesDownstream) {
		return nil, false
	}
	return o.MessagesDownstream, true
}

// HasMessagesDownstream returns a boolean if a field has been set.
func (o *DeviceStats) HasMessagesDownstream() bool {
	if o != nil && !IsNil(o.MessagesDownstream) {
		return true
	}

	return false
}

// SetMessagesDownstream gets a reference to the given string and assigns it to the MessagesDownstream field.
func (o *DeviceStats) SetMessagesDownstream(v string) {
	o.MessagesDownstream = &v
}

// GetSessionCount returns the SessionCount field value if set, zero value otherwise.
func (o *DeviceStats) GetSessionCount() int32 {
	if o == nil || IsNil(o.SessionCount) {
		var ret int32
		return ret
	}
	return *o.SessionCount
}

// GetSessionCountOk returns a tuple with the SessionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStats) GetSessionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SessionCount) {
		return nil, false
	}
	return o.SessionCount, true
}

// HasSessionCount returns a boolean if a field has been set.
func (o *DeviceStats) HasSessionCount() bool {
	if o != nil && !IsNil(o.SessionCount) {
		return true
	}

	return false
}

// SetSessionCount gets a reference to the given int32 and assigns it to the SessionCount field.
func (o *DeviceStats) SetSessionCount(v int32) {
	o.SessionCount = &v
}

func (o DeviceStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BytesUpstream) {
		toSerialize["bytesUpstream"] = o.BytesUpstream
	}
	if !IsNil(o.BytesDownstream) {
		toSerialize["bytesDownstream"] = o.BytesDownstream
	}
	if !IsNil(o.MessagesUpstream) {
		toSerialize["messagesUpstream"] = o.MessagesUpstream
	}
	if !IsNil(o.MessagesDownstream) {
		toSerialize["messagesDownstream"] = o.MessagesDownstream
	}
	if !IsNil(o.SessionCount) {
		toSerialize["sessionCount"] = o.SessionCount
	}
	return toSerialize, nil
}

type NullableDeviceStats struct {
	value *DeviceStats
	isSet bool
}

func (v NullableDeviceStats) Get() *DeviceStats {
	return v.value
}

func (v *NullableDeviceStats) Set(val *DeviceStats) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceStats) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceStats(val *DeviceStats) *NullableDeviceStats {
	return &NullableDeviceStats{value: val, isSet: true}
}

func (v NullableDeviceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


