/*
The Span API

API for device, collection, output and firmware management

API version: 5.0.5 contented-jamila
Contact: dev@lab5e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanapi

import (
	"encoding/json"
)

// checks if the VerifyCertificateBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyCertificateBody{}

// VerifyCertificateBody Verify a certificate
type VerifyCertificateBody struct {
	GatewayId *string `json:"gatewayId,omitempty"`
	DeviceId *string `json:"deviceId,omitempty"`
	Certificate *string `json:"certificate,omitempty"`
}

// NewVerifyCertificateBody instantiates a new VerifyCertificateBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyCertificateBody() *VerifyCertificateBody {
	this := VerifyCertificateBody{}
	return &this
}

// NewVerifyCertificateBodyWithDefaults instantiates a new VerifyCertificateBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyCertificateBodyWithDefaults() *VerifyCertificateBody {
	this := VerifyCertificateBody{}
	return &this
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *VerifyCertificateBody) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyCertificateBody) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *VerifyCertificateBody) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *VerifyCertificateBody) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *VerifyCertificateBody) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyCertificateBody) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *VerifyCertificateBody) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *VerifyCertificateBody) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *VerifyCertificateBody) GetCertificate() string {
	if o == nil || IsNil(o.Certificate) {
		var ret string
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyCertificateBody) GetCertificateOk() (*string, bool) {
	if o == nil || IsNil(o.Certificate) {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *VerifyCertificateBody) HasCertificate() bool {
	if o != nil && !IsNil(o.Certificate) {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given string and assigns it to the Certificate field.
func (o *VerifyCertificateBody) SetCertificate(v string) {
	o.Certificate = &v
}

func (o VerifyCertificateBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyCertificateBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GatewayId) {
		toSerialize["gatewayId"] = o.GatewayId
	}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Certificate) {
		toSerialize["certificate"] = o.Certificate
	}
	return toSerialize, nil
}

type NullableVerifyCertificateBody struct {
	value *VerifyCertificateBody
	isSet bool
}

func (v NullableVerifyCertificateBody) Get() *VerifyCertificateBody {
	return v.value
}

func (v *NullableVerifyCertificateBody) Set(val *VerifyCertificateBody) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyCertificateBody) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyCertificateBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyCertificateBody(val *VerifyCertificateBody) *NullableVerifyCertificateBody {
	return &NullableVerifyCertificateBody{value: val, isSet: true}
}

func (v NullableVerifyCertificateBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyCertificateBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


